---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

# # kube-prometheus-stack

- name: Create Grafana secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-secret
        namespace: monitoring
      type: Opaque
      data:
        admin-user: "{{ grafana_admin_username | b64encode }}"
        admin-password: "{{ grafana_admin_password | b64encode }}"

- name: kube-prometheus-stack
  kubernetes.core.helm:
    name: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: false
    values: "{{ lookup('template', 'values.j2') | from_yaml  }}"

# fortigate-exporter
- name: Create Fortigate secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: fortigate-secret
        namespace: monitoring
      type: Opaque
      stringData:
        fortigate-key.yaml: |
          "{{ fortigate_url }}":
            token: {{ fortigate_api_token }}
            probes:
              exclude:
                - System/SensorInfo
                - BGP/Neighbors/IPv4
                - BGP/Neighbors/IPv6
                - Network/Dns/Latency
                - System/Central-Management/Status
                - System/HAStatistics
                - System/Ha-peer
                - System/Interface/Transceivers
                - System/Performance/Status
                - System/Ntp/Status
                - System/HAChecksum
                - Switch/ManagedSwitch

- name: Deploy fortigate-exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: fortigate-exporter
        namespace: monitoring
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: fortigate-exporter
        template:
          metadata:
            labels:
              app: fortigate-exporter
          spec:
            containers:
              - name: fortigate-exporter
                image: prometheuscommunity/fortigate-exporter:latest
                args:
                  - "-auth-file=/config/fortigate-key.yaml"
                  - "-insecure"
                ports:
                  - containerPort: 9710
                volumeMounts:
                  - name: config-volume
                    mountPath: /config/fortigate-key.yaml
                    subPath: fortigate-key.yaml
                    readOnly: true
            volumes:
              - name: config-volume
                secret:
                  secretName: fortigate-secret

- name: Expose fortigate-exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: fortigate-exporter
        namespace: monitoring
      spec:
        selector:
          app: fortigate-exporter
        ports:
          - port: 9710
            targetPort: 9710

# pve-exporter
- name: Create Proxmox VE secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pve-secret
        namespace: monitoring
      type: Opaque
      stringData:
        pve.yaml: |
          default:
            user: "{{ pve_user }}"
            token_name: "{{ pve_token_name }}"
            token_value: "{{ pve_token_value }}"
            verify_ssl: false

- name: Deploy pve-exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pve-exporter
        namespace: monitoring
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: pve-exporter
        template:
          metadata:
            labels:
              app: pve-exporter
          spec:
            containers:
              - name: pve-exporter
                image: prompve/prometheus-pve-exporter:latest
                args:
                  - "--config=/config/pve.yaml"
                ports:
                  - containerPort: 9221
                volumeMounts:
                  - name: config-volume
                    mountPath: /config/pve.yaml
                    subPath: pve.yaml
                    readOnly: true
            volumes:
              - name: config-volume
                secret:
                  secretName: pve-secret

- name: Expose pve-exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: pve-exporter
        namespace: monitoring
      spec:
        selector:
          app: pve-exporter
        ports:
          - port: 9221
            targetPort: 9221  

# dashboards
- name: Create Grafana dashboard configmap for fortigate-exporter
  kubernetes.core.k8s:
    state: present
    force: yes
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-fortigate-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
        annotations:
          grafana_folder: "Fortigate"
      data:
        fortigate.json: |
          {{ lookup('file', 'dashboards/fortigate.json') }}

- name: Create Grafana dashboard configmap for pve-exporter
  kubernetes.core.k8s:
    state: present
    force: yes
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-pve-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
        annotations:
          grafana_folder: "PVE"
      data:
        proxmox.json: |
          {{ lookup('file', 'dashboards/proxmox.json') }}

- name: Create Grafana dashboard configmap for monitoring overview
  kubernetes.core.k8s:
    state: present
    force: yes
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-monitoring-overview-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
        annotations:
          grafana_folder: "Monitoring"
      data:
        monitoring_overview.json: |
          {{ lookup('file', 'dashboards/monitoring_overview.json') }}