{
 "title": "Fortigate",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(fortigate_interface_transmit_bytes_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - fortigate_last_reboot_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wan1 usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(fortigate_interface_receive_bytes_total{name=\"wan1\", instance=\"$instance\"}[1m])",
     "legendFormat": "bytes received"
    },
    {
     "expr": "rate(fortigate_interface_transmit_bytes_total{name=\"wan1\", instance=\"$instance\"}[1m])",
     "legendFormat": "bytes sent"
    }
   ]
  },
  {
   "title": "wan1 status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fortigate_interface_link_up{name=\"wan1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}