grafana:
  enabled: true
  admin:
    existingSecret: grafana-secret
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: NodePort
    nodePort: 30000

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30001
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false