---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Disable swap if enabled #as recommended in https://github.com/k3s-io/k3s-ansible/issues/147
  ansible.builtin.command: swapoff -a
  become: yes
  when: ansible_swaptotal_mb > 0

- name: Disable swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'
  become: yes

- name: Grow /dev/sdb1 to fill the disk
  ansible.builtin.command: "growpart /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 1"
  register: growpart_result
  changed_when: "'CHANGED' in growpart_result.stdout"
  failed_when:
    - growpart_result.rc != 0
    - "'NOCHANGE' not in growpart_result.stdout"
  become: yes

- name: Resize VG and LV to use all free space
  community.general.lvol:
    vg: "{{ root_vg }}"
    lv: "{{ root_lv }}"
    size: 100%PVS
    resizefs: true
  become: yes