---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Disable swap if enabled #as recommended in https://github.com/k3s-io/k3s-ansible/issues/147
  ansible.builtin.command: swapoff -a
  become: yes
  when: ansible_swaptotal_mb > 0

- name: Disable swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'
  become: yes

